disabled_rules:
  - trailing_whitespace
  - line_length
  
opt_in_rules:
  - empty_count
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_string
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

line_length:
  warning: 120
  error: 200
  
type_body_length:
  warning: 300
  error: 500
  
file_length:
  warning: 500
  error: 1000
  
function_body_length:
  warning: 50
  error: 100
  
excluded:
  - .build
  - .swiftpm
  - Package.swift
  - Tests