name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Set timezone for consistent test results
  TZ: UTC

jobs:
  test-macos:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.1.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage
      env:
        # Force timezone for tests
        NSTimeZone: UTC
    - name: Generate coverage report
      run: |
        xcrun llvm-cov export -format="lcov" \
          .build/debug/SwiftDateParserPackageTests.xctest/Contents/MacOS/SwiftDateParserPackageTests \
          -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.lcov
        flags: unittests
        name: codecov-umbrella
        
  test-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:6.0
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
      env:
        TZ: UTC
      
  lint:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.1.app
    - name: Install SwiftLint
      run: brew install swiftlint
    - name: Run SwiftLint
      run: swiftlint --strict