name: Test SwiftDateParser

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    
    - name: Build
      run: swift build -c release
    
    - name: Run tests
      run: swift test
    
    - name: Run comparison tests
      run: |
        python3 -m venv test_venv
        source test_venv/bin/activate
        pip install python-dateutil
        python test_comparison.py
        ./.build/release/TestComparison
  
  test-linux:
    runs-on: ubuntu-latest
    container: swift:6.0
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install Python and dependencies
      run: |
        apt-get update
        apt-get install -y python3 python3-pip python3-venv
    
    - name: Build
      run: swift build -c release
    
    - name: Run tests
      run: swift test
    
    - name: Run comparison tests
      run: |
        python3 -m venv test_venv
        source test_venv/bin/activate
        pip install python-dateutil
        python3 test_comparison.py
        ./.build/release/TestComparison
  
  test-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "6.0"
    
    - name: Build
      run: swift build -c release
    
    - name: Run tests
      run: swift test